### PR TITLE
fixed CS and added needed grunt commands to create a artifact

### LINKED ISSUE #194: Create grunt commands to generate a artifact zip
In Yoast SEO we have grunt commands, like grunt update-version, grunt copy:artifact and grunt compress:artifact which updates then version in the relevant files. This needs to be present in Yoast SEO woocommerce too.

### PR DESCRIPTION
**Pull request by dutchmartin**
## Summary

This PR can be summarized in the following changelog entry:

* Adds `copy:artifact` and `compress:artifact` command to Grunt to create an artifact zip.

## Relevant technical choices:

* using the grunt compress package
* using the grunt copy package
* adding a command that builds the project and creates a zipped artifact using the above named packages

## Test instructions

This PR can be tested by following these steps:

1. Ensure you have all development dependency's for the project by running `yarn install`
2.  Execute the new command `create:artifact`, this is an alias that contains the following commands: 
    * `update-version`
    *  `build`
    * `copy:artifact` 
    * `compress:artifact`
3. check if the command does what is described below
`create:artifact: Create a zipped artifact from a fresh build`
`copy:artifact: Copy the needed files to the ./artifact folder`
`compress:artifact: Create a compressed zip from the ./artifact folder`

Fixes #194

### CODE REVIEW

File: grunt/config/copy.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+	artifactFiles: {
+		files: [
+			{
+				expand: true,
+				cwd: ".",
+				src: [
+					// folders to copy
+					"classes/**",
+					"vendor/**",
+					"js/**",
```
Comment (moorscode) [inline grunt/config/copy.js]: The files in the `js/src` directory should not be included in the artifact.
Please exclude these.

File: grunt/config/copy.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+				expand: true,
+				cwd: ".",
+				src: [
+					// folders to copy
+					"classes/**",
+					"vendor/**",
+					"js/*.min.js",
+					"languages/**",
+					// files to copy
+					"wpseo-woocommerce.php",
```
Comment (jcomack) [inline grunt/config/copy.js]: As per feedback given on https://github.com/Yoast/wpseo-news/pull/366/files, wouldn't you want to use a wildcard here as well?

**Comment by jcomack** [comment]
Acceptance done 👍
